[target.wasm32-unknown-unknown]
rustflags = [
  "-C", "link-arg=--initial-memory=65536", # 初期メモリを64KB(1ページ)に制限
  "-C", "link-arg=--max-memory=65536",     # 最大メモリも64KBに制限
  "-C", "link-arg=-zstack-size=1024",      # Rust内部スタックを1KBに縮小
]