[package]
name = "dyne-embedded"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# 依存なし（標準ライブラリのみで計算します）

[profile.release]
panic = "abort"
opt-level = "z" # サイズ優先
lto = true